Add explicit circuit breaker configuration for java agent
tacitknowledge/newrelic pull request #2
Opened 2018-12-17 15:22 UTC by olegburca

2018-12-17 21:15 UTC, acondrat commented
@olegburca why not implementing this as resource properties?
This is a library cookbook. There is no single reference to `@node` attributes in the current template as it is build using resource properties. I don't see any reason to change that.

2018-12-17 21:30 UTC, acondrat requested changes
- Do not use node attributes!
 - Implement this as part of `newrelic_agent_java` resource
 - Make sure resource properties have default values as per https://docs.newrelic.com/docs/agents/java-agent/configuration/java-agent-configuration-config-file#circuit-breaker
 - Update README.md documenting the new properties

2018-12-19 09:45 UTC, olegburca commented
@acondrat, please recheck.

2018-12-19 10:35 UTC, acondrat commented
Please delete unused node attributes.
Please update readme.

2018-12-20 08:00 UTC, olegburca commented
@acondrat, please recheck.

2018-12-20 10:54 UTC, acondrat requested changes

2018-12-20 10:54 UTC, acondrat commented on templates/default/agent/newrelic.yml.erb
> +  # Circuit breacker configuration
fix typo

2018-12-20 10:56 UTC, merged